import enum


class UserRole(str, enum.Enum):
    ADMIN = "ADMIN"
    SUPERVISOR = "SUPERVISOR"
    VERIFIER = "VERIFIER"
    OPERATOR = "OPERATOR"
    AUDITOR = "AUDITOR"
    READ_ONLY = "READ_ONLY"


class DocumentStatus(str, enum.Enum):
    UPLOADED = "UPLOADED"
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    OCR_PROCESSING = "OCR_PROCESSING"
    OCR_COMPLETE = "OCR_COMPLETE"
    EXTRACTION_PROCESSING = "EXTRACTION_PROCESSING"
    EXTRACTION_COMPLETE = "EXTRACTION_COMPLETE"
    VALIDATING = "VALIDATING"
    VALIDATION_COMPLETE = "VALIDATION_COMPLETE"
    REQUIRES_VERIFICATION = "REQUIRES_VERIFICATION"
    NEEDS_VERIFICATION = "NEEDS_VERIFICATION"   # Backward-compat alias
    VERIFIED = "VERIFIED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"
